name: flatland-rl

channels:
  - conda-forge
  - defaults

dependencies:
  - psutil==5.7.2
  - pip==20.2.3
  - python==3.6.8
  - networkx==2.5
  - pycairo==1.20.0
  - autopep8==1.5.4
  - tabulate==0.8.7
  - tqdm==4.51.0
  # - pip:
  #     - flatland-rl==2.2.2
  #     - tensorboard==2.3.0
  #     - wandb==0.9.5
